export const roadmapData = Object.freeze({
  updatedAt: '2026-06-21',
  overallPercent: 65,
  defaultAdminEndpoint: 'http://127.0.0.1:47910/admin/session-state',
  headline: 'LOGH VII 부활 개발 대시보드',
  progressNote:
    '문서 기준 55%에서 로비 네이티브 리마스터, 배포 EXE, 성계 실제 별점 재추출/콘텐츠 DB 재빌드, 커맨드라인 로그인 부트스트랩, post-load 좌석/유닛 스트림/focus-cell 기본값을 보정. HUD/명령 admission/함선 표시/전술맵과 0x0b01 명령 루프 전까지 서버 오픈 판정은 보류.',
  summary:
    '기준은 매뉴얼대로 플레이 가능한 상태입니다. 현재 배포 EXE는 서버가 켜진 상태에서 로그인 자동 부트스트랩으로 월드까지 진입하고, 로비는 레터박스가 아니라 이 PC 기준 네이티브 1920x1080 배치를 사용합니다. 성계 좌표는 page101-bg.jpg 실제 별점 원 중심으로 재잠금했고 콘텐츠 DB도 재생성했습니다. post-load unit stream과 focus-cell 기본값으로 전략 root current는 채워지지만 자연 0x0b01 명령은 아직 열리지 않습니다. 최신 RE상 남은 차단점은 HUD 선택목록 row hit, category resolve, command row dispatch입니다. 함선 표시/전술맵/행성·천체·소속 콘텐츠/전 화면 리마스터도 서버 오픈 전 P0입니다.',
  corrections: [
    '그리드 클릭은 현재 동작하는 것으로 사용자 확인됨. 새 로드맵에서는 완료로 분리하고 나머지 UI 기능 검증으로 초점을 이동.',
    '전략 지형은 서버가 0x0313/0x0315로 내려준다. 따라서 이동 가능/불가능 그리드는 서버 데이터와 클라 파서가 함께 맞아야 한다.',
    '성계 좌표는 PDF 주석/검은 선/모서리가 아니라 page101-bg.jpg 실제 원형 별점 중심 기준으로 재추출했다. Iserlohn은 서버 셀 [53,12], UI 셀 [54,13]이고 Fezzan은 서버 셀 [51,38], UI 셀 [52,39]다.',
    'content/*.json은 초기 시드/추출 원본이다. 배포 콘텐츠는 content/logh7-content.db, 계정은 logh7-runtime/state/accounts.sqlite, 월드 스냅샷은 SQLite repository가 맡는다.',
    '레터박스/4:3 보존 기본값은 폐기. 기본 playable EXE는 lobby-res + lobby-native-layout으로 1920x1080 로비 배치를 사용하며, 다른 해상도는 두 패치를 같은 크기로 재생성해야 한다.',
    'Pretendard는 EXE face 패치만으로 끝나지 않는다. 런처/ui_explorer가 per-user 폰트 등록을 먼저 수행하고, EXE는 font-cleartype 패치까지 적용해야 굴림 같은 낡은 GDI 인상을 피한다.',
    '로그인은 클릭 자동입력이 아니라 클라이언트 내부 InputFromCommandLine 부트스트랩 패치로 처리한다. 서버가 켜지면 ginei00 계정으로 conn1→conn2→conn3 월드 진입까지 이어진다.',
    'post-load action-list 좌석은 LOGH_POSTLOAD_ACTION_LIST_SEATS=1로 기본 제공한다. 초기 0x0f02 스폰 레코드는 과거 HUD 오염 리스크 때문에 계속 미니멀 유지.',
    'post-load unit stream과 focus-cell은 기본 제공한다. 실클라 root watcher가 currentRaw11178=2550을 확인했지만, 자연 0x0b01/0x0b07은 아직 미해결.',
    '자연 0x0b01의 남은 병목은 좌표가 아니라 FUN_004fd100 HUD mode/category gate, FUN_004f6600 선택목록 row hit-test, FUN_004f5cb0/FUN_004f58c0 명령 row dispatch다.',
  ],
  indicators: [
    { label: '서버 오픈 판정', value: '아직 불가', tone: 'danger' },
    { label: '실클라 진입', value: '가능', tone: 'good' },
    { label: '리마스터 방향', value: '네이티브', tone: 'good' },
    { label: '콘텐츠 기준', value: '매뉴얼', tone: 'warn' },
  ],
  contentCoverage: [
    { label: '성계', value: '80', detail: '래스터 실제 별점 좌표 재추출 및 SQLite 콘텐츠 DB 재빌드 완료. 미니맵/명령 라이브 회귀 필요' },
    { label: '행성', value: '281+', detail: '이름/궤도 중심. 경제/천체 속성 보강 필요' },
    { label: '요새', value: '6', detail: '매뉴얼/콘텐츠 DB 기준 검증 대상' },
    { label: '인물', value: '부분', detail: '공식 앵커와 추정 티어를 분리 유지' },
  ],
  milestones: [
    {
      title: 'M1 실제 플레이 세션',
      percent: 68,
      status: '진행',
      items: [
        { text: '로그인 핸드셰이크와 로비 진입', state: 'done' },
        { text: '배포 EXE의 서버 로그인 자동 부트스트랩', state: 'done' },
        { text: '월드 진입과 전략 그리드 표시', state: 'done' },
        { text: '그리드 클릭 입력', state: 'done' },
        { text: '로비 메인→게임 시작→환경 설정 라이브 클릭 확인', state: 'done' },
        { text: '로비 모든 버튼의 라이브 클릭 회귀 확인', state: 'active' },
        { text: '게임 세션 상태 어드민 관측', state: 'active' },
        { text: 'post-load 좌석/action-list 레코드 기본 제공', state: 'done' },
        { text: '전략 root current cell 서버 기본값', state: 'done' },
        { text: 'HUD 선택목록/명령 admission 스냅샷 도구', state: 'done' },
        { text: '자연 0x0b01/0x0b07 명령 루프', state: 'active' },
        { text: 'HUD NO DATA/글리프 잔여 패널 식별', state: 'active' },
      ],
    },
    {
      title: 'M2 매뉴얼 콘텐츠 완성',
      percent: 50,
      status: 'P0',
      items: [
        { text: '성계 점 위치 재추출', state: 'done' },
        { text: 'one-cell 회랑 마스크 재생성', state: 'done' },
        { text: '새 좌표 미니맵/명령 루프 실클라 회귀', state: 'active' },
        { text: '행성/천체/소속/경제 필드의 출처 등급화', state: 'active' },
        { text: '세션 시작상태와 진영별 소유/원수/요직 보강', state: 'todo' },
        { text: '미구현 매뉴얼 커맨드 구현 목록 고정', state: 'todo' },
      ],
    },
    {
      title: 'M3 리마스터/현지화',
      percent: 62,
      status: '진행',
      items: [
        { text: 'String.txt/rsrc 한국어 문구 정리', state: 'active' },
        { text: 'Pretendard, Pretendard JP, Pretendard Std 배포/설치', state: 'done' },
        { text: 'GDI 전역 폰트 패치 기본 스택 포함', state: 'done' },
        { text: 'GDI ClearType 품질 패치 기본 스택 포함', state: 'done' },
        { text: '로비 1920x1080 네이티브 좌표 재배치 라이브 검증', state: 'done' },
        { text: '전 게임 화면 네이티브 배치 리마스터', state: 'active' },
      ],
    },
    {
      title: 'M4 배포와 모딩',
      percent: 55,
      status: '진행',
      items: [
        { text: '플레이어용 EXE 빌드와 로컬 서버 런처', state: 'done' },
        { text: '콘텐츠 DB/시나리오/모드 경로 런타임 포함', state: 'done' },
        { text: '계정/월드 영속 저장소 SQLite 기본화', state: 'done' },
        { text: '서버 공지 운영 경로 문서화', state: 'done' },
        { text: '클라이언트 패키지에 최신 EXE/폰트/MsgDat 반영', state: 'done' },
        { text: 'Docker/RDB 운영 전환 계획', state: 'todo' },
      ],
    },
  ],
  priorityQueue: [
    { rank: 'P0', title: '0x0b01 command admission 라이브', detail: '세계 진입 후 selection row hit, hudModeF4=2, categoryD6, command row dispatch를 snapshot으로 확인하고 SelectGrid factory까지 연다.' },
    { rank: 'P0', title: '성계 지형 라이브 회귀', detail: '재추출된 실제 별점 좌표와 재생성한 passable mask를 0x0313/0x0315 실클라 전략맵, 미니맵, 명령 루프에서 확인.' },
    { rank: 'P0', title: '매뉴얼 콘텐츠 갭 폐쇄', detail: '행성·천체·소속·요직·시작 세션을 출처 등급과 함께 채움.' },
    { rank: 'P0', title: '라이브 로비 회귀', detail: 'NewChar/Lottery/Delete/Session과 공지 수신을 실제 클라에서 다시 클릭 확인.' },
    { rank: 'P1', title: '전 화면 네이티브 UI', detail: '로비처럼 설정/생성/세션/월드 패널도 시스템 해상도 기준 좌표와 텍스처를 재배치.' },
    { rank: 'P1', title: '현지화 품질', detail: '어색한 문구와 폰트 fallback을 제거하고 CJK/Latin/JP 혼용을 확인.' },
    { rank: 'P1', title: '배포물 단일화', detail: 'playable EXE, 런처, 폰트, 서버 런타임, 어드민 토큰을 한 경로로 묶음.' },
  ],
  serverNotice: {
    env: 'LOGH_LOBBY_ANNOUNCE_TEXT',
    fallbackEnv: 'LOGH_SESSION_ANNOUNCE_TEXT',
    cli: 'npm run server:auth -- --announcement "서버 점검 안내"',
    cp949Cli: 'npm run server:auth -- --announcement-cp949-hex <cp949 hex>',
    admin: 'Authorization: Bearer <token> + PUT http://127.0.0.1:47910/admin/notice {"cp949Hex":"..."}',
    route: '로비 로그인 OK 직후 conn2 extra inner로 공지 notify 전송',
  },
  exe: {
    buildCommand: 'python -m tools.logh7_build_playable_client --deploy',
    launcherCommand: 'npm run package --prefix client',
    expectedClient: 'client/dist/logh7-client/exe/G7MTClient.exe',
    sha256: '15ed8a35ea3891374096b25d43878e74a6abbf97242b32ecf357ca4c577768e0',
  },
});
